import json
import os

rules = []

def add_rule(rid, cat, desc, check, spawns=None):
    if spawns is None:
        spawns = []
    rules.append({
        "id": rid,
        "category": cat,
        "description": desc,
        "trigger_condition": "edit_file",
        "check_condition": check,
        "spawns": spawns
    })

# STYLE
add_rule(1, "STYLE", "Function names must be snake_case.", r'regex pattern: r"def [a-z_0-9]+\("', [])
add_rule(2, "STYLE", "Class names must be CamelCase.", r'regex pattern: r"class [A-Z][a-zA-Z0-9]+\("', [])
add_rule(3, "STYLE", "Constants must be UPPER_SNAKE_CASE.", r'regex pattern: r"^[A-Z_0-9]+ = "', [])
add_rule(4, "STYLE", "Indentation must be exactly 4 spaces.", r'regex pattern: r"^ {4}[^ ]"', [])
add_rule(5, "STYLE", "No trailing whitespace allowed.", r'regex:no pattern match: [ \t]+$', [])
add_rule(6, "STYLE", "Maximum line length is 88 characters.", 'subprocess:ruff check passes', [])
add_rule(7, "STYLE", "All imports must be grouped: stdlib first, then third-party, then local.", 'subprocess:ruff check passes', [])
add_rule(8, "STYLE", "No wildcard imports allowed.", r'regex:no pattern match: from \w+ import \*', [])
add_rule(9, "STYLE", "Variables must be snake_case.", r'regex pattern: r"[a-z_0-9]+ = "', [])
add_rule(10, "STYLE", "Use single quotes for string literals.", r"regex pattern: r'.*'", [])
add_rule(11, "STYLE", "Use double quotes for docstrings.", r'regex pattern: r"\"\"\"(.*)\"\"\""', [])
add_rule(12, "STYLE", "Functions under 5 lines must have no inline comments.", 'ast_check:line_count <= 5', [])
add_rule(13, "STYLE", "Comments must have a space after the hash symbol.", r'regex pattern: r"# [A-Z]"', [])
add_rule(14, "STYLE", "No consecutive blank lines greater than 2.", r'regex:no pattern match: \n\n\n', [])
add_rule(15, "STYLE", "Use f-strings over .format().", r'regex pattern: r"f\'.*\'"', [])
add_rule(16, "STYLE", "No % formatting allowed.", r'regex:no pattern match: %\s*\w+', [])
add_rule(17, "STYLE", "Docstrings must use Sphinx format.", r'regex pattern: r":param|:return:"', [])
add_rule(18, "STYLE", "Return type annotations are required for all functions.", 'ast_check:has_type_hints', [])
add_rule(19, "STYLE", "Argument type annotations are required for all functions.", 'ast_check:has_type_hints', [])
add_rule(20, "STYLE", "All methods must have self or cls as first argument.", r'regex pattern: r"def \w+\((self|cls)"', [])
add_rule(21, "STYLE", "Private methods must start with an underscore.", r'regex pattern: r"def _[a-z_]+\("', [])
add_rule(22, "STYLE", "Dictionary keys must be strings explicitly.", r'regex pattern: r"\{[\'\"].*[\'\"]:"', [])
add_rule(23, "STYLE", "List comprehensions preferred over map function.", r'regex:no pattern match: map\(', [])
add_rule(24, "STYLE", "Generator expressions preferred over filter function.", r'regex:no pattern match: filter\(', [])
add_rule(25, "STYLE", "Use 'is' for None comparisons.", r'regex pattern: r"is None"', [])
add_rule(26, "STYLE", "Do not use == True or == False.", r'regex:no pattern match: == True|== False', [])
add_rule(27, "STYLE", "Explicit Exception names must be used in except blocks.", 'ast_check:no_bare_except', [])
add_rule(28, "STYLE", "Use context managers for file operations.", r'regex pattern: r"with open\("', [])
add_rule(29, "STYLE", "All functions must have docstrings.", 'ast_check:has_docstring', [12, 91, 118])
add_rule(30, "STYLE", "Module level docstring is required.", 'ast_check:has_docstring', [])

# STRUCTURAL
add_rule(31, "STRUCTURAL", "File must have a main block execution guard.", r'regex pattern: r"if __name__ == \"__main__\":"', [])
add_rule(32, "STRUCTURAL", "Classes should have an __init__ method.", r'regex pattern: r"def __init__\("', [])
add_rule(33, "STRUCTURAL", "Methods should not exceed 100 lines.", 'ast_check:line_count <= 100', [])
add_rule(34, "STRUCTURAL", "Classes should not exceed 500 lines.", 'ast_check:line_count <= 500', [])
add_rule(35, "STRUCTURAL", "No deeply nested loops (greater than 3 levels).", r'regex:no pattern match: for.*:\n\s*for.*:\n\s*for.*:\n\s*for', [])
add_rule(36, "STRUCTURAL", "Maximum 5 arguments per function.", 'subprocess:ruff check passes', [])
add_rule(37, "STRUCTURAL", "No global state modification allowed.", r'regex:no pattern match: global \w+', [])
add_rule(38, "STRUCTURAL", "Helper functions must be prefixed with utils_.", r'regex pattern: r"def utils_[a-z_]+\("', [])
add_rule(39, "STRUCTURAL", "Config files must be parsed using json or yaml load.", r'regex pattern: r"json\.load|yaml\.safe_load"', [])
add_rule(40, "STRUCTURAL", "FastAPI app instances must be named app.", r'regex pattern: r"app = FastAPI\("', [])
add_rule(41, "STRUCTURAL", "Routers must be named router.", r'regex pattern: r"router = APIRouter\("', [])
add_rule(42, "STRUCTURAL", "I/O bound functions must be async.", r'regex pattern: r"async def"', [])
add_rule(43, "STRUCTURAL", "Models must inherit from Pydantic BaseModel.", r'regex pattern: r"class \w+\(BaseModel\):"', [])
add_rule(44, "STRUCTURAL", "No file may exceed 200 lines.", 'ast_check:line_count <= 200', [91, 17])
add_rule(45, "STRUCTURAL", "Controllers must be placed in controllers directory.", 'file_exists:controllers', [])
add_rule(46, "STRUCTURAL", "Services must be placed in services directory.", 'file_exists:services', [])
add_rule(47, "STRUCTURAL", "Utilities must be placed in utils directory.", 'file_exists:utils', [])
add_rule(48, "STRUCTURAL", "Data Transfer Objects must be explicitly defined with DTO suffix.", r'regex pattern: r"class \w+DTO\("', [])
add_rule(49, "STRUCTURAL", "Responses must use a generic ResponseWrapper.", r'regex pattern: r"ResponseWrapper"', [])
add_rule(50, "STRUCTURAL", "Repositories must use SQLAlchemy Session.", r'regex pattern: r"Session"', [])
add_rule(51, "STRUCTURAL", "Custom exceptions must inherit from AppError.", r'regex pattern: r"class \w+\(AppError\):"', [])
add_rule(52, "STRUCTURAL", "Decorators must be used for authentication.", r'regex pattern: r"@requires_auth"', [])
add_rule(53, "STRUCTURAL", "Enums must be used for defining statuses.", r'regex pattern: r"class \w+\(Enum\):"', [])
add_rule(54, "STRUCTURAL", "Factory pattern must be used for complex object creation.", r'regex pattern: r"def create_\w+\("', [])
add_rule(55, "STRUCTURAL", "No function may exceed 50 lines.", 'ast_check:line_count <= 50', [56, 103])
add_rule(56, "STRUCTURAL", "All modules must be registered in module_registry.json.", 'json_contains:module_registry.json', [])
add_rule(57, "STRUCTURAL", "Test files must end in _test.py.", r'regex pattern: r".*_test\.py"', [])
add_rule(58, "STRUCTURAL", "Fixtures must reside in conftest.py.", 'file_exists:conftest.py', [])
add_rule(59, "STRUCTURAL", "Interfaces must inherit from ABC.", r'regex pattern: r"class \w+\(ABC\):"', [])
add_rule(60, "STRUCTURAL", "Only a single class is permitted per file.", 'subprocess:ruff check passes', [])
add_rule(61, "STRUCTURAL", "Pydantic must be used for all data validation.", r'regex pattern: r"from pydantic"', [])
add_rule(62, "STRUCTURAL", "TypeVars must be named explicitly.", r'regex pattern: r"\w+ = TypeVar\("', [])
add_rule(63, "STRUCTURAL", "Try blocks should not exceed 5 lines.", 'ast_check:line_count <= 5', [])
add_rule(64, "STRUCTURAL", "Finally blocks are required for cleanup operations.", r'regex pattern: r"finally:"', [])
add_rule(65, "STRUCTURAL", "Custom exceptions must initialize with messages.", r'regex pattern: r"super\(\)\.__init__\("', [])
add_rule(66, "STRUCTURAL", "Loggers must be instantiated with __name__.", r'regex pattern: r"logging\.getLogger\(__name__\)"', [])
add_rule(67, "STRUCTURAL", "Config must be injected via Dependency Injection.", r'regex pattern: r"Depends\(get_config\)"', [])
add_rule(68, "STRUCTURAL", "Data classes should be used for internal state.", r'regex pattern: r"@dataclass"', [])
add_rule(69, "STRUCTURAL", "Yield is preferred for processing large sequences.", r'regex pattern: r"yield "', [])
add_rule(70, "STRUCTURAL", "Properties must be used for computed class attributes.", r'regex pattern: r"@property"', [])

# SECURITY
add_rule(71, "SECURITY", "Passwords must be hashed before storage.", r'regex pattern: r"hash_password\("', [])
add_rule(72, "SECURITY", "Authentication tokens must use JWT.", r'regex pattern: r"jwt\.encode\("', [])
add_rule(73, "SECURITY", "Secrets must be loaded from the environment.", r'regex pattern: r"os\.getenv\("', [])
add_rule(74, "SECURITY", "No hardcoded API keys are allowed.", r'regex:no pattern match: api_key = [\'"][A-Za-z0-9]+[\'"]', [])
add_rule(75, "SECURITY", "CORS headers are required for all endpoints.", r'regex pattern: r"CORSMiddleware"', [])
add_rule(76, "SECURITY", "CSRF protection must be enabled.", r'regex pattern: r"csrf_protect\("', [])
add_rule(77, "SECURITY", "Rate limiting must be applied to public routes.", r'regex pattern: r"@limiter\.limit"', [])
add_rule(78, "SECURITY", "Content-Security-Policy header must be set.", r'regex pattern: r"Content-Security-Policy"', [])
add_rule(79, "SECURITY", "SQL injection prevention: no f-strings in database queries.", r'regex:no pattern match: execute\(f".*"\)', [])
add_rule(80, "SECURITY", "XSS prevention: user input must be escaped in HTML.", r'regex pattern: r"escape\("', [])
add_rule(81, "SECURITY", "Use safe_load for YAML parsing to prevent code execution.", r'regex pattern: r"yaml\.safe_load\("', [])
add_rule(82, "SECURITY", "Use defusedxml for parsing XML to prevent external entity attacks.", r'regex pattern: r"from defusedxml"', [])
add_rule(83, "SECURITY", "No hardcoded secrets allowed in the codebase.", r'regex:no pattern match: password|secret|key', [134])
add_rule(84, "SECURITY", "Auth tokens must expire in less than 1 hour.", r'regex pattern: r"exp=datetime\.utcnow\(\) \+ timedelta\(minutes=[1-5][0-9]\)"', [])
add_rule(85, "SECURITY", "Cookies must be marked as secure and httponly.", r'regex pattern: r"secure=True, httponly=True"', [])
add_rule(86, "SECURITY", "SSL verification must not be disabled in requests.", r'regex:no pattern match: verify=False', [])
add_rule(87, "SECURITY", "Hashlib must use sha256 or a stronger algorithm.", r'regex:no pattern match: hashlib\.md5|hashlib\.sha1', [])
add_rule(88, "SECURITY", "The secrets module must be used for cryptographically secure randomness.", r'regex pattern: r"import secrets"', [])
add_rule(89, "SECURITY", "The eval and exec functions are strictly prohibited.", r'regex:no pattern match: eval\(|exec\(', [])
add_rule(90, "SECURITY", "Subprocess calls must not use shell=True.", r'regex:no pattern match: shell=True', [])
add_rule(91, "SECURITY", "Timeout must be specified on all HTTP calls.", r'regex pattern: r"timeout=[0-9.]+"', [])
add_rule(92, "SECURITY", "PII data must be masked in application output.", r'regex pattern: r"mask_pii\("', [])
add_rule(93, "SECURITY", "Prevent directory traversal by securing file paths.", r'regex pattern: r"os\.path\.abspath|secure_filename"', [])
add_rule(94, "SECURITY", "S3 buckets must not have public-read access control lists.", r"regex:no pattern match: ACL='public-read'", [])
add_rule(95, "SECURITY", "Debug mode must be explicitly disabled in production.", r'regex pattern: r"debug=False"', [])
add_rule(96, "SECURITY", "JWT verification must be strictly enforced.", r'regex pattern: r"verify_signature=True"', [])
add_rule(97, "SECURITY", "Role-based access control must be verified before sensitive operations.", r'regex pattern: r"check_role\("', [])
add_rule(98, "SECURITY", "User input sizes must be limited to 1MB.", r'regex pattern: r"Content-Length.*< 1048576"', [])
add_rule(99, "SECURITY", "Audit logging is required for all administrative actions.", r'regex pattern: r"audit_logger\.info\("', [])
add_rule(100, "SECURITY", "User IDs must be obfuscated in application logs.", r'regex pattern: r"obfuscate_id\("', [])

# CONDITIONAL
add_rule(101, "CONDITIONAL", "If a route uses the POST method, it must return a 201 status code.", r'regex pattern: r"status_code=201"', [])
add_rule(102, "CONDITIONAL", "If a route uses the DELETE method, it must return a 204 status code.", r'regex pattern: r"status_code=204"', [])
add_rule(103, "CONDITIONAL", "If a file exceeds 200 lines, it must be split into multiple modules.", 'ast_check:line_count <= 200', [])
add_rule(104, "CONDITIONAL", "If a database model is updated, the Pydantic schema must also be updated.", 'rule_satisfied:43', [])
add_rule(105, "CONDITIONAL", "If caching is used, a Time-To-Live (TTL) must be explicitly set.", r'regex pattern: r"ttl=[0-9]+"', [])
add_rule(106, "CONDITIONAL", "If a route is async, it must use the await keyword internally.", r'regex pattern: r"await "', [])
add_rule(107, "CONDITIONAL", "If data is paginated, the response must include total_pages metadata.", r'regex pattern: r"total_pages"', [])
add_rule(108, "CONDITIONAL", "If a new environment variable is added, it must be documented in README.md.", 'file_exists:README.md', [])
add_rule(109, "CONDITIONAL", "If HTTP requests are made, the httpx library is preferred over requests.", r'regex:no pattern match: import requests', [])
add_rule(110, "CONDITIONAL", "If a dependency is injected, it must enable caching.", r'regex pattern: r"Depends\(.*use_cache=True\)"', [])
add_rule(111, "CONDITIONAL", "If a list is returned from an endpoint, it must be wrapped in a dictionary.", r'regex pattern: r"\{\"data\": \["', [])
add_rule(112, "CONDITIONAL", "If a custom Exception is raised, it must be logged prior.", r'regex pattern: r"logger\.error.*raise"', [])
add_rule(113, "CONDITIONAL", "If debug mode is true, verbose logging must be enabled.", 'rule_satisfied:95', [])
add_rule(114, "CONDITIONAL", "If a retry loop is implemented, a backoff factor must be configured.", r'regex pattern: r"backoff_factor"', [])
add_rule(115, "CONDITIONAL", "If a metric is emitted, it must include identifying tags.", r'regex pattern: r"tags=\{"', [])
add_rule(116, "CONDITIONAL", "If an email is sent, it must be executed as a background task.", r'regex pattern: r"background_tasks\.add_task"', [])
add_rule(117, "CONDITIONAL", "If the database is queried, a session context manager must be used.", r'regex pattern: r"with get_session\(\):"', [])
add_rule(118, "CONDITIONAL", "If an HTTP call is added, Rule 91 must be satisfied.", 'rule_satisfied:91', [])
add_rule(119, "CONDITIONAL", "If a custom JSON response is returned, the content-type must be application/json.", r'regex pattern: r"application/json"', [])
add_rule(120, "CONDITIONAL", "If an external API fails, the service must raise a 502 Bad Gateway.", r'regex pattern: r"status_code=502"', [])
add_rule(121, "CONDITIONAL", "If a UUID is generated, it must strictly be UUID4.", r'regex pattern: r"uuid4\("', [])
add_rule(122, "CONDITIONAL", "If a timezone is parsed, it must be normalized to UTC.", r'regex pattern: r"timezone\.utc"', [])
add_rule(123, "CONDITIONAL", "If a file is uploaded, it must be scanned for viruses.", r'regex pattern: r"scan_file\("', [])
add_rule(124, "CONDITIONAL", "If a user password is changed, all active sessions must be invalidated.", r'regex pattern: r"invalidate_sessions\("', [])
add_rule(125, "CONDITIONAL", "If an account is deleted, a soft delete is preferred over a hard delete.", r'regex pattern: r"is_deleted=True"', [])
add_rule(126, "CONDITIONAL", "If monetary values are calculated, the Decimal type must be used.", r'regex pattern: r"Decimal\("', [])
add_rule(127, "CONDITIONAL", "If float values are compared, math.isclose must be utilized.", r'regex pattern: r"math\.isclose\("', [])
add_rule(128, "CONDITIONAL", "If the random module is used, a seed is required for deterministic testing.", r'regex pattern: r"random\.seed\("', [])
add_rule(129, "CONDITIONAL", "If a singleton is instantiated, thread safety via locks is required.", r'regex pattern: r"Lock\(\)"', [])
add_rule(130, "CONDITIONAL", "If a subprocess command fails, stderr must be explicitly captured.", r'regex pattern: r"capture_output=True"', [])

# CONTRADICTORY
add_rule(131, "CONTRADICTORY", "All functions must use type hints for all arguments. (Conflicts with Rule 132)", 'ast_check:has_type_hints', [])
add_rule(132, "CONTRADICTORY", "Functions under 10 lines must avoid type hints to reduce visual clutter. (Conflicts with Rule 131)", r'regex:no pattern match: :[ a-zA-Z]+', [])
add_rule(133, "CONTRADICTORY", "Environment variables must be parsed strictly using a schema. (Conflicts with Rule 134)", r'regex pattern: r"EnvSchema\.parse_obj"', [])
add_rule(134, "CONTRADICTORY", "Secrets must be hardcoded in dev mode for ease of use. (Conflicts with Rule 133)", r'regex pattern: r"secret_key=\"dev_secret\""', [29])
add_rule(135, "CONTRADICTORY", "All database interactions must use raw SQL queries for performance reasons. (Conflicts with Rule 136)", r'regex pattern: r"cursor\.execute\(\"SELECT"', [])
add_rule(136, "CONTRADICTORY", "All database interactions must use an ORM to prevent SQL injection. (Conflicts with Rule 135)", r'regex pattern: r"session\.query\("', [])
add_rule(137, "CONTRADICTORY", "External API calls must catch all exceptions generically to prevent crashes. (Conflicts with Rule 138)", r'regex pattern: r"except Exception:"', [])
add_rule(138, "CONTRADICTORY", "External API calls must only catch specific exceptions like HTTPError. (Conflicts with Rule 137)", r'regex pattern: r"except httpx\.HTTPError:"', [])
add_rule(139, "CONTRADICTORY", "Logging must capture every request payload entirely for auditing purposes. (Conflicts with Rule 140)", r'regex pattern: r"logger\.info\(request\.body\)"', [])
add_rule(140, "CONTRADICTORY", "Logging must never capture request payloads to protect PII. (Conflicts with Rule 139)", r'regex:no pattern match: logger\.info\(request\.body\)', [])
add_rule(141, "CONTRADICTORY", "All endpoints must require an Authorization header. (Conflicts with Rule 144)", r'regex pattern: r"Header\(.*Authorization\)"', [])
add_rule(142, "CONTRADICTORY", "All functions must have inline comments explaining internal logic. (Conflicts with Rule 143)", r'regex pattern: r".*#.*"', [])
add_rule(143, "CONTRADICTORY", "Functions under 5 lines must have NO inline comments. (Conflicts with Rule 142)", 'ast_check:line_count <= 5', [])
add_rule(144, "CONTRADICTORY", "Public endpoints like /health must accept unauthenticated requests. (Conflicts with Rule 141)", r'regex:no pattern match: Header\(.*Authorization\)', [])
add_rule(145, "CONTRADICTORY", "Modules should import specific functions individually (from x import y). (Conflicts with Rule 146)", r'regex pattern: r"from \w+ import \w+"', [])
add_rule(146, "CONTRADICTORY", "Modules should import the whole package to prevent namespace collisions (import x). (Conflicts with Rule 145)", r'regex pattern: r"import \w+"', [])
add_rule(147, "CONTRADICTORY", "JSON responses must use camelCase keys for JavaScript compatibility. (Conflicts with Rule 148)", r'regex pattern: r"userName:"', [])
add_rule(148, "CONTRADICTORY", "JSON responses must use snake_case keys for Python consistency. (Conflicts with Rule 147)", r'regex pattern: r"user_name:"', [])
add_rule(149, "CONTRADICTORY", "Temporary files must be created in /tmp directly. (Conflicts with Rule 150)", r'regex pattern: r"open\(\'/tmp/.*\'\)"', [])
add_rule(150, "CONTRADICTORY", "Temporary files must use the tempfile module for secure generation. (Conflicts with Rule 149)", r'regex pattern: r"tempfile\.NamedTemporaryFile"', [])

# Sort rules by ID to ensure sequence
rules.sort(key=lambda x: x["id"])

# Generate markdown
output = []
output.append("# ENGINEERING STANDARDS")
output.append("")

current_category = ""
for rule in rules:
    if rule["category"] != current_category:
        current_category = rule["category"]
        output.append(f"## {current_category} RULES")
        output.append("")
    
    output.append(f"### Rule {rule['id']}")
    output.append(f"**Category**: {rule['category']}")
    output.append(f"**Description**: {rule['description']}")
    output.append(f"**Trigger condition**: {rule['trigger_condition']}")
    output.append(f"**Check condition**: {rule['check_condition']}")
    output.append(f"**Spawns**: {json.dumps(rule['spawns'])}")
    output.append("")

output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "environment", "ENGINEERING_STANDARDS.md")
with open(output_path, "w") as f:
    f.write("\n".join(output))

print("DONE")
